# Generated by Django 3.2.9 on 2021-12-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentsUser', '0002_commentspost_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentspost',
            old_name='reply',
            new_name='parent',
        ),
    ]
