# Generated by Django 3.2.9 on 2021-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_newspost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
