# Generated by Django 3.2.9 on 2021-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_newspost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
