# Generated by Django 3.2.9 on 2021-12-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_remove_newspost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
