# Generated by Django 3.2.9 on 2021-12-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_newspost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='author',
        ),
    ]
