# Generated by Django 3.2.9 on 2021-12-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usernewspost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNewsPost',
        ),
    ]
